name: scribble
description: Scribble is a lightweight library for freehand drawing in Flutter
  supporting pressure, variable line width and more!
version: 0.10.0+1
repository: https://github.com/timcreatedit/scribble
issue_tracker: https://github.com/timcreatedit/scribble/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0
  perfect_freehand: ^2.3.2
  simpli: ^0.1.1+2
  value_notifier_tools: ^0.1.2

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  freezed: ^3.0.4
  json_serializable: ^6.9.4
  lintervention: ^0.1.1
  melos: ">=5.2.1 <7.0.0"
  mocktail: ^1.0.4

flutter:
  uses-material-design: true